#!/usr/bin/env bash
#This script is displaying 11 lines, the 9th line is Hi while the others are 'Best School'
number=0; while [$number -lt 10]; do echo "Best School"; if [$number -eq 8]; then echo "Hi"; fi; number = $((number+1)); done
